export const header = [
  'USUBJID',
  'PARAMCD',
  'AVISITN',
  'CRIT5FL',
  'CRIT5',
  'SEX',
  'TRT01P',
  'RACEGR1',
  'CHG',
  'AVAL',
];
const data = [
  {
    USUBJID: 'X-104949-32062001',
    PARAMCD: 'PAMAYO',
    AVISITN: 20,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'ABC Y MG',
    RACEGR1: 'WHITE',
    CHG: -4,
    AVAL: 0,
  },
  {
    USUBJID: 'X-104949-32062001',
    PARAMCD: 'PAMAYO',
    AVISITN: 28,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'ABC Y MG',
    RACEGR1: 'WHITE',
    CHG: -4,
    AVAL: 0,
  },
  {
    USUBJID: 'X-104949-32062001',
    PARAMCD: 'PAMAYO',
    AVISITN: 36,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'ABC Y MG',
    RACEGR1: 'WHITE',
    CHG: -4,
    AVAL: 0,
  },
  {
    USUBJID: 'X-104949-32062001',
    PARAMCD: 'PAMAYO',
    AVISITN: 44,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'ABC Y MG',
    RACEGR1: 'WHITE',
    CHG: -4,
    AVAL: 0,
  },
  {
    USUBJID: 'X-104949-32062001',
    PARAMCD: 'PAMAYO',
    AVISITN: 52,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'ABC Y MG',
    RACEGR1: 'WHITE',
    CHG: -4,
    AVAL: 0,
  },
  {
    USUBJID: 'X-105084-24002004',
    PARAMCD: 'PAMAYO',
    AVISITN: 4,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'ABC X MG',
    RACEGR1: 'WHITE',
    CHG: -2,
    AVAL: 1.3,
  },
  {
    USUBJID: 'X-105084-24002004',
    PARAMCD: 'PAMAYO',
    AVISITN: 8,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'ABC X MG',
    RACEGR1: 'WHITE',
    CHG: -2,
    AVAL: 1.3,
  },
  {
    USUBJID: 'X-105084-24002004',
    PARAMCD: 'PAMAYO',
    AVISITN: 12,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'ABC X MG',
    RACEGR1: 'WHITE',
    CHG: -2.3,
    AVAL: 1,
  },
  {
    USUBJID: 'X-105084-24002004',
    PARAMCD: 'PAMAYO',
    AVISITN: 20,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'ABC X MG',
    RACEGR1: 'WHITE',
    CHG: -1.6,
    AVAL: 1.7,
  },
  {
    USUBJID: 'X-105084-24002004',
    PARAMCD: 'PAMAYO',
    AVISITN: 28,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'ABC X MG',
    RACEGR1: 'WHITE',
    CHG: -2.6,
    AVAL: 0.7,
  },
  {
    USUBJID: 'X-105084-24002004',
    PARAMCD: 'PAMAYO',
    AVISITN: 36,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'ABC X MG',
    RACEGR1: 'WHITE',
    CHG: -2.3,
    AVAL: 1,
  },
  {
    USUBJID: 'X-105084-24002004',
    PARAMCD: 'PAMAYO',
    AVISITN: 44,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'ABC X MG',
    RACEGR1: 'WHITE',
    CHG: -2.3,
    AVAL: 1,
  },
  {
    USUBJID: 'X-105084-24002004',
    PARAMCD: 'PAMAYO',
    AVISITN: 52,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'ABC X MG',
    RACEGR1: 'WHITE',
    CHG: -2.3,
    AVAL: 1,
  },
  {
    USUBJID: 'X-110959-60651009',
    PARAMCD: 'PAMAYO',
    AVISITN: 12,
    CRIT5FL: 'N',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'Placebo',
    RACEGR1: 'WHITE',
    CHG: 0.7,
    AVAL: 3,
  },
  {
    USUBJID: 'X-110959-60651009',
    PARAMCD: 'PAMAYO',
    AVISITN: 20,
    CRIT5FL: 'N',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'Placebo',
    RACEGR1: 'WHITE',
    CHG: 0.7,
    AVAL: 3,
  },
  {
    USUBJID: 'X-110959-60651009',
    PARAMCD: 'PAMAYO',
    AVISITN: 28,
    CRIT5FL: 'N',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'Placebo',
    RACEGR1: 'WHITE',
    CHG: 0.7,
    AVAL: 3,
  },
  {
    USUBJID: 'X-110959-60651009',
    PARAMCD: 'PAMAYO',
    AVISITN: 36,
    CRIT5FL: 'N',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'Placebo',
    RACEGR1: 'WHITE',
    CHG: 0.7,
    AVAL: 3,
  },
  {
    USUBJID: 'X-110959-60651009',
    PARAMCD: 'PAMAYO',
    AVISITN: 44,
    CRIT5FL: 'N',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'Placebo',
    RACEGR1: 'WHITE',
    CHG: 0.7,
    AVAL: 3,
  },
  {
    USUBJID: 'X-110959-60651009',
    PARAMCD: 'PAMAYO',
    AVISITN: 52,
    CRIT5FL: 'N',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'Placebo',
    RACEGR1: 'WHITE',
    CHG: -0.3,
    AVAL: 2,
  },
  {
    USUBJID: 'X-115908-15062001',
    PARAMCD: 'PAMAYO',
    AVISITN: 20,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'Placebo',
    RACEGR1: 'WHITE',
    CHG: -2,
    AVAL: 2,
  },
  {
    USUBJID: 'X-115908-15062001',
    PARAMCD: 'PAMAYO',
    AVISITN: 28,
    CRIT5FL: 'N',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'Placebo',
    RACEGR1: 'WHITE',
    CHG: 0,
    AVAL: 4,
  },
  {
    USUBJID: 'X-116818-52072002',
    PARAMCD: 'PAMAYO',
    AVISITN: 36,
    CRIT5FL: 'N',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'Placebo',
    RACEGR1: 'NON-WHITE',
    CHG: -0.4,
    AVAL: 4.3,
  },
  {
    USUBJID: 'X-116818-52072006',
    PARAMCD: 'PAMAYO',
    AVISITN: 52,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'Placebo',
    RACEGR1: 'NON-WHITE',
    CHG: -5,
    AVAL: 1,
  },
  {
    USUBJID: 'X-120516-53062002',
    PARAMCD: 'PAMAYO',
    AVISITN: 4,
    CRIT5FL: 'N',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'Placebo',
    RACEGR1: 'WHITE',
    CHG: 0,
    AVAL: 3,
  },
  {
    USUBJID: 'X-120516-53062002',
    PARAMCD: 'PAMAYO',
    AVISITN: 8,
    CRIT5FL: 'N',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'Placebo',
    RACEGR1: 'WHITE',
    CHG: 2.3,
    AVAL: 5.3,
  },
  {
    USUBJID: 'X-120608-60762001',
    PARAMCD: 'PAMAYO',
    AVISITN: 52,
    CRIT5FL: 'N',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'Placebo',
    RACEGR1: 'NON-WHITE',
    CHG: -1.4,
    AVAL: 3.3,
  },
  {
    USUBJID: 'X-123192-48012003',
    PARAMCD: 'PAMAYO',
    AVISITN: 4,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'Placebo',
    RACEGR1: 'WHITE',
    CHG: -3,
    AVAL: 2.7,
  },
  {
    USUBJID: 'X-123192-48012003',
    PARAMCD: 'PAMAYO',
    AVISITN: 8,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'Placebo',
    RACEGR1: 'WHITE',
    CHG: -4.7,
    AVAL: 1,
  },
  {
    USUBJID: 'X-123192-48012003',
    PARAMCD: 'PAMAYO',
    AVISITN: 12,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'Placebo',
    RACEGR1: 'WHITE',
    CHG: -3.7,
    AVAL: 2,
  },
  {
    USUBJID: 'X-123192-48012003',
    PARAMCD: 'PAMAYO',
    AVISITN: 20,
    CRIT5FL: 'N',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'Placebo',
    RACEGR1: 'WHITE',
    CHG: -0.7,
    AVAL: 5,
  },
  {
    USUBJID: 'X-123192-48012008',
    PARAMCD: 'PAMAYO',
    AVISITN: 4,
    CRIT5FL: 'N',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'Placebo',
    RACEGR1: 'WHITE',
    CHG: 0,
    AVAL: 6,
  },
  {
    USUBJID: 'X-12676-60242001',
    PARAMCD: 'PAMAYO',
    AVISITN: 52,
    CRIT5FL: 'N',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'Placebo',
    RACEGR1: 'WHITE',
    CHG: -0.7,
    AVAL: 4.7,
  },
  {
    USUBJID: 'X-303334-33442001',
    PARAMCD: 'PAMAYO',
    AVISITN: 8,
    CRIT5FL: 'N',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'ABC Y MG',
    RACEGR1: 'NON-WHITE',
    CHG: 0.1,
    AVAL: 3.7,
  },
  {
    USUBJID: 'X-303334-33442001',
    PARAMCD: 'PAMAYO',
    AVISITN: 12,
    CRIT5FL: 'N',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'ABC Y MG',
    RACEGR1: 'NON-WHITE',
    CHG: 0.7,
    AVAL: 4.3,
  },
  {
    USUBJID: 'X-34870-32032006',
    PARAMCD: 'PAMAYO',
    AVISITN: 8,
    CRIT5FL: 'N',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'Placebo',
    RACEGR1: 'WHITE',
    CHG: 1,
    AVAL: 6,
  },
  {
    USUBJID: 'X-34870-32032009',
    PARAMCD: 'PAMAYO',
    AVISITN: 8,
    CRIT5FL: 'N',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'ABC Y MG',
    RACEGR1: 'WHITE',
    CHG: -0.7,
    AVAL: 4,
  },
  {
    USUBJID: 'X-34870-32032009',
    PARAMCD: 'PAMAYO',
    AVISITN: 12,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'ABC Y MG',
    RACEGR1: 'WHITE',
    CHG: -2.7,
    AVAL: 2,
  },
  {
    USUBJID: 'X-34870-32032009',
    PARAMCD: 'PAMAYO',
    AVISITN: 20,
    CRIT5FL: 'N',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'ABC Y MG',
    RACEGR1: 'WHITE',
    CHG: 1.3,
    AVAL: 6,
  },
  {
    USUBJID: 'X-42109-35052001',
    PARAMCD: 'PAMAYO',
    AVISITN: 36,
    CRIT5FL: 'N',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'Placebo',
    RACEGR1: 'NON-WHITE',
    CHG: -1.3,
    AVAL: 4,
  },
  {
    USUBJID: 'X-42109-35052004',
    PARAMCD: 'PAMAYO',
    AVISITN: 0,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'ABC X MG',
    RACEGR1: 'NON-WHITE',
    CHG: -2.3,
    AVAL: 0.7,
  },
  {
    USUBJID: 'X-42109-35052004',
    PARAMCD: 'PAMAYO',
    AVISITN: 4,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'ABC X MG',
    RACEGR1: 'NON-WHITE',
    CHG: -3,
    AVAL: 0,
  },
  {
    USUBJID: 'X-42109-35052004',
    PARAMCD: 'PAMAYO',
    AVISITN: 8,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'ABC X MG',
    RACEGR1: 'NON-WHITE',
    CHG: -1.7,
    AVAL: 1.3,
  },
  {
    USUBJID: 'X-42109-35052004',
    PARAMCD: 'PAMAYO',
    AVISITN: 12,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'ABC X MG',
    RACEGR1: 'NON-WHITE',
    CHG: -2,
    AVAL: 1,
  },
  {
    USUBJID: 'X-42109-35052004',
    PARAMCD: 'PAMAYO',
    AVISITN: 20,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'ABC X MG',
    RACEGR1: 'NON-WHITE',
    CHG: -2.7,
    AVAL: 0.3,
  },
  {
    USUBJID: 'X-42109-35052004',
    PARAMCD: 'PAMAYO',
    AVISITN: 28,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'ABC X MG',
    RACEGR1: 'NON-WHITE',
    CHG: -2.3,
    AVAL: 0.7,
  },
  {
    USUBJID: 'X-42109-35052004',
    PARAMCD: 'PAMAYO',
    AVISITN: 36,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'ABC X MG',
    RACEGR1: 'NON-WHITE',
    CHG: -2,
    AVAL: 1,
  },
  {
    USUBJID: 'X-42109-35052004',
    PARAMCD: 'PAMAYO',
    AVISITN: 44,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'ABC X MG',
    RACEGR1: 'NON-WHITE',
    CHG: -2,
    AVAL: 1,
  },
  {
    USUBJID: 'X-42109-35052004',
    PARAMCD: 'PAMAYO',
    AVISITN: 52,
    CRIT5FL: 'N',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'ABC X MG',
    RACEGR1: 'NON-WHITE',
    CHG: 1.7,
    AVAL: 4.7,
  },
  {
    USUBJID: 'X-42810-61171002',
    PARAMCD: 'PAMAYO',
    AVISITN: 0,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'Placebo',
    RACEGR1: 'WHITE',
    CHG: -2.3,
    AVAL: 0.7,
  },
  {
    USUBJID: 'X-42810-61171002',
    PARAMCD: 'PAMAYO',
    AVISITN: 4,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'Placebo',
    RACEGR1: 'WHITE',
    CHG: -1.6,
    AVAL: 1.4,
  },
  {
    USUBJID: 'X-42810-61171002',
    PARAMCD: 'PAMAYO',
    AVISITN: 8,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'Placebo',
    RACEGR1: 'WHITE',
    CHG: -1.7,
    AVAL: 1.3,
  },
  {
    USUBJID: 'X-42810-61171002',
    PARAMCD: 'PAMAYO',
    AVISITN: 12,
    CRIT5FL: 'N',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'Placebo',
    RACEGR1: 'WHITE',
    CHG: 2.7,
    AVAL: 5.7,
  },
  {
    USUBJID: 'X-42810-61171002',
    PARAMCD: 'PAMAYO',
    AVISITN: 20,
    CRIT5FL: 'N',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'Placebo',
    RACEGR1: 'WHITE',
    CHG: -0.3,
    AVAL: 2.7,
  },
  {
    USUBJID: 'X-42810-61171002',
    PARAMCD: 'PAMAYO',
    AVISITN: 28,
    CRIT5FL: 'N',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'Placebo',
    RACEGR1: 'WHITE',
    CHG: -0.3,
    AVAL: 2.7,
  },
  {
    USUBJID: 'X-42810-61171002',
    PARAMCD: 'PAMAYO',
    AVISITN: 36,
    CRIT5FL: 'N',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'Placebo',
    RACEGR1: 'WHITE',
    CHG: 1.7,
    AVAL: 4.7,
  },
  {
    USUBJID: 'X-42810-61171002',
    PARAMCD: 'PAMAYO',
    AVISITN: 44,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'Placebo',
    RACEGR1: 'WHITE',
    CHG: -1,
    AVAL: 2,
  },
  {
    USUBJID: 'X-42810-61171002',
    PARAMCD: 'PAMAYO',
    AVISITN: 52,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'Placebo',
    RACEGR1: 'WHITE',
    CHG: -1,
    AVAL: 2,
  },
  {
    USUBJID: 'X-46275-17132014',
    PARAMCD: 'PAMAYO',
    AVISITN: 4,
    CRIT5FL: 'N',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'Placebo',
    RACEGR1: 'WHITE',
    CHG: 2,
    AVAL: 4,
  },
  {
    USUBJID: 'X-467771-33472001',
    PARAMCD: 'PAMAYO',
    AVISITN: 20,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'Placebo',
    RACEGR1: 'NON-WHITE',
    CHG: -2,
    AVAL: 2.3,
  },
  {
    USUBJID: 'X-467771-33472001',
    PARAMCD: 'PAMAYO',
    AVISITN: 28,
    CRIT5FL: 'N',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'Placebo',
    RACEGR1: 'NON-WHITE',
    CHG: -0.3,
    AVAL: 4,
  },
  {
    USUBJID: 'X-467771-33472001',
    PARAMCD: 'PAMAYO',
    AVISITN: 36,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'Placebo',
    RACEGR1: 'NON-WHITE',
    CHG: -1.3,
    AVAL: 3,
  },
  {
    USUBJID: 'X-467771-33472001',
    PARAMCD: 'PAMAYO',
    AVISITN: 44,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'Placebo',
    RACEGR1: 'NON-WHITE',
    CHG: -1.3,
    AVAL: 3,
  },
  {
    USUBJID: 'X-467771-33472001',
    PARAMCD: 'PAMAYO',
    AVISITN: 52,
    CRIT5FL: 'N',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'Placebo',
    RACEGR1: 'NON-WHITE',
    CHG: -0.3,
    AVAL: 4,
  },
  {
    USUBJID: 'X-50734-33372001',
    PARAMCD: 'PAMAYO',
    AVISITN: 8,
    CRIT5FL: 'N',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'Placebo',
    RACEGR1: 'NON-WHITE',
    CHG: -1,
    AVAL: 3,
  },
  {
    USUBJID: 'X-50734-33372001',
    PARAMCD: 'PAMAYO',
    AVISITN: 12,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'Placebo',
    RACEGR1: 'NON-WHITE',
    CHG: -2.7,
    AVAL: 1.3,
  },
  {
    USUBJID: 'X-50734-33372001',
    PARAMCD: 'PAMAYO',
    AVISITN: 20,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'Placebo',
    RACEGR1: 'NON-WHITE',
    CHG: -1.3,
    AVAL: 2.7,
  },
  {
    USUBJID: 'X-50734-33372001',
    PARAMCD: 'PAMAYO',
    AVISITN: 28,
    CRIT5FL: 'N',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'Placebo',
    RACEGR1: 'NON-WHITE',
    CHG: -1,
    AVAL: 3,
  },
  {
    USUBJID: 'X-50734-33372002',
    PARAMCD: 'PAMAYO',
    AVISITN: 36,
    CRIT5FL: 'N',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'Placebo',
    RACEGR1: 'NON-WHITE',
    CHG: 0.6,
    AVAL: 4,
  },
  {
    USUBJID: 'X-50992-19092001',
    PARAMCD: 'PAMAYO',
    AVISITN: 52,
    CRIT5FL: 'N',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'Placebo',
    RACEGR1: 'NON-WHITE',
    CHG: 1.7,
    AVAL: 2.7,
  },
  {
    USUBJID: 'X-52516-33252001',
    PARAMCD: 'PAMAYO',
    AVISITN: 0,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'ABC X MG',
    RACEGR1: 'NON-WHITE',
    CHG: -2.7,
    AVAL: 3.3,
  },
  {
    USUBJID: 'X-52516-33252001',
    PARAMCD: 'PAMAYO',
    AVISITN: 4,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'ABC X MG',
    RACEGR1: 'NON-WHITE',
    CHG: -6,
    AVAL: 0,
  },
  {
    USUBJID: 'X-52516-33252001',
    PARAMCD: 'PAMAYO',
    AVISITN: 8,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'ABC X MG',
    RACEGR1: 'NON-WHITE',
    CHG: -5.3,
    AVAL: 0.7,
  },
  {
    USUBJID: 'X-52516-33252001',
    PARAMCD: 'PAMAYO',
    AVISITN: 12,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'ABC X MG',
    RACEGR1: 'NON-WHITE',
    CHG: -5.7,
    AVAL: 0.3,
  },
  {
    USUBJID: 'X-52516-33252001',
    PARAMCD: 'PAMAYO',
    AVISITN: 20,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'ABC X MG',
    RACEGR1: 'NON-WHITE',
    CHG: -6,
    AVAL: 0,
  },
  {
    USUBJID: 'X-52516-33252001',
    PARAMCD: 'PAMAYO',
    AVISITN: 28,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'ABC X MG',
    RACEGR1: 'NON-WHITE',
    CHG: -6,
    AVAL: 0,
  },
  {
    USUBJID: 'X-52516-33252001',
    PARAMCD: 'PAMAYO',
    AVISITN: 36,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'ABC X MG',
    RACEGR1: 'NON-WHITE',
    CHG: -6,
    AVAL: 0,
  },
  {
    USUBJID: 'X-52516-33252001',
    PARAMCD: 'PAMAYO',
    AVISITN: 44,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'ABC X MG',
    RACEGR1: 'NON-WHITE',
    CHG: -6,
    AVAL: 0,
  },
  {
    USUBJID: 'X-52516-33252001',
    PARAMCD: 'PAMAYO',
    AVISITN: 52,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'ABC X MG',
    RACEGR1: 'NON-WHITE',
    CHG: -6,
    AVAL: 0,
  },
  {
    USUBJID: 'X-53907-57032001',
    PARAMCD: 'PAMAYO',
    AVISITN: 8,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'Placebo',
    RACEGR1: 'WHITE',
    CHG: -2.7,
    AVAL: 1,
  },
  {
    USUBJID: 'X-53907-57032001',
    PARAMCD: 'PAMAYO',
    AVISITN: 12,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'Placebo',
    RACEGR1: 'WHITE',
    CHG: -2.7,
    AVAL: 1,
  },
  {
    USUBJID: 'X-53907-57032001',
    PARAMCD: 'PAMAYO',
    AVISITN: 20,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'Placebo',
    RACEGR1: 'WHITE',
    CHG: -2.7,
    AVAL: 1,
  },
  {
    USUBJID: 'X-53907-57032001',
    PARAMCD: 'PAMAYO',
    AVISITN: 28,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'Placebo',
    RACEGR1: 'WHITE',
    CHG: -2.7,
    AVAL: 1,
  },
  {
    USUBJID: 'X-53907-57032001',
    PARAMCD: 'PAMAYO',
    AVISITN: 36,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'Placebo',
    RACEGR1: 'WHITE',
    CHG: -2.7,
    AVAL: 1,
  },
  {
    USUBJID: 'X-53907-57032001',
    PARAMCD: 'PAMAYO',
    AVISITN: 44,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'Placebo',
    RACEGR1: 'WHITE',
    CHG: -2.7,
    AVAL: 1,
  },
  {
    USUBJID: 'X-53907-57032001',
    PARAMCD: 'PAMAYO',
    AVISITN: 52,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'Placebo',
    RACEGR1: 'WHITE',
    CHG: -3.4,
    AVAL: 0.3,
  },
  {
    USUBJID: 'X-54037-31012001',
    PARAMCD: 'PAMAYO',
    AVISITN: 8,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'ABC Y MG',
    RACEGR1: 'WHITE',
    CHG: -4,
    AVAL: 2,
  },
  {
    USUBJID: 'X-54037-31012001',
    PARAMCD: 'PAMAYO',
    AVISITN: 12,
    CRIT5FL: 'N',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'ABC Y MG',
    RACEGR1: 'WHITE',
    CHG: 0,
    AVAL: 6,
  },
  {
    USUBJID: 'X-952299-33412001',
    PARAMCD: 'PAMAYO',
    AVISITN: 28,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'Placebo',
    RACEGR1: 'NON-WHITE',
    CHG: -1.7,
    AVAL: 2,
  },
  {
    USUBJID: 'X-952299-33412001',
    PARAMCD: 'PAMAYO',
    AVISITN: 36,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'Placebo',
    RACEGR1: 'NON-WHITE',
    CHG: -2,
    AVAL: 1.7,
  },
  {
    USUBJID: 'X-952299-33412001',
    PARAMCD: 'PAMAYO',
    AVISITN: 44,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'Placebo',
    RACEGR1: 'NON-WHITE',
    CHG: -2.7,
    AVAL: 1,
  },
  {
    USUBJID: 'X-952299-33412001',
    PARAMCD: 'PAMAYO',
    AVISITN: 52,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'Placebo',
    RACEGR1: 'NON-WHITE',
    CHG: -3.7,
    AVAL: 0,
  },
  {
    USUBJID: 'X-996817-46002001',
    PARAMCD: 'PAMAYO',
    AVISITN: 4,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'ABC Y MG',
    RACEGR1: 'WHITE',
    CHG: -5.7,
    AVAL: 0,
  },
  {
    USUBJID: 'X-996817-46002001',
    PARAMCD: 'PAMAYO',
    AVISITN: 8,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'ABC Y MG',
    RACEGR1: 'WHITE',
    CHG: -4.7,
    AVAL: 1,
  },
  {
    USUBJID: 'X-996817-46002001',
    PARAMCD: 'PAMAYO',
    AVISITN: 12,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'ABC Y MG',
    RACEGR1: 'WHITE',
    CHG: -5.4,
    AVAL: 0.3,
  },
  {
    USUBJID: 'X-996817-46002001',
    PARAMCD: 'PAMAYO',
    AVISITN: 20,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'ABC Y MG',
    RACEGR1: 'WHITE',
    CHG: -5.7,
    AVAL: 0,
  },
  {
    USUBJID: 'X-996817-46002001',
    PARAMCD: 'PAMAYO',
    AVISITN: 28,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'ABC Y MG',
    RACEGR1: 'WHITE',
    CHG: -4,
    AVAL: 1.7,
  },
  {
    USUBJID: 'X-996817-46002001',
    PARAMCD: 'PAMAYO',
    AVISITN: 36,
    CRIT5FL: 'N',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'ABC Y MG',
    RACEGR1: 'WHITE',
    CHG: 0.3,
    AVAL: 6,
  },
  {
    USUBJID: 'Y-105084-24003007',
    PARAMCD: 'PAMAYO',
    AVISITN: 0,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'ABC Y MG',
    RACEGR1: 'WHITE',
    CHG: -2.3,
    AVAL: 1.7,
  },
  {
    USUBJID: 'Y-105084-24003007',
    PARAMCD: 'PAMAYO',
    AVISITN: 4,
    CRIT5FL: 'N',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'F',
    TRT01P: 'ABC Y MG',
    RACEGR1: 'WHITE',
    CHG: 2,
    AVAL: 6,
  },
  {
    USUBJID: 'Y-134989-61303005',
    PARAMCD: 'PAMAYO',
    AVISITN: 28,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'Placebo',
    RACEGR1: 'WHITE',
    CHG: -4.4,
    AVAL: 1.3,
  },
  {
    USUBJID: 'Y-134989-61303005',
    PARAMCD: 'PAMAYO',
    AVISITN: 36,
    CRIT5FL: 'N',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'Placebo',
    RACEGR1: 'WHITE',
    CHG: 0.3,
    AVAL: 6,
  },
  {
    USUBJID: 'Y-135965-33333002',
    PARAMCD: 'PAMAYO',
    AVISITN: 12,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'Placebo',
    RACEGR1: 'NON-WHITE',
    CHG: -3.6,
    AVAL: 1.7,
  },
  {
    USUBJID: 'Y-135965-33333002',
    PARAMCD: 'PAMAYO',
    AVISITN: 20,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'Placebo',
    RACEGR1: 'NON-WHITE',
    CHG: -5.3,
    AVAL: 0,
  },
  {
    USUBJID: 'Y-135965-33333002',
    PARAMCD: 'PAMAYO',
    AVISITN: 28,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'Placebo',
    RACEGR1: 'NON-WHITE',
    CHG: -5.3,
    AVAL: 0,
  },
  {
    USUBJID: 'Y-135965-33333002',
    PARAMCD: 'PAMAYO',
    AVISITN: 36,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'Placebo',
    RACEGR1: 'NON-WHITE',
    CHG: -5.3,
    AVAL: 0,
  },
  {
    USUBJID: 'Y-135965-33333002',
    PARAMCD: 'PAMAYO',
    AVISITN: 44,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'Placebo',
    RACEGR1: 'NON-WHITE',
    CHG: -5.3,
    AVAL: 0,
  },
  {
    USUBJID: 'Y-135965-33333002',
    PARAMCD: 'PAMAYO',
    AVISITN: 52,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'Placebo',
    RACEGR1: 'NON-WHITE',
    CHG: -5.3,
    AVAL: 0,
  },
  {
    USUBJID: 'Y-29080-17093007',
    PARAMCD: 'PAMAYO',
    AVISITN: 20,
    CRIT5FL: 'N',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'Placebo',
    RACEGR1: 'NON-WHITE',
    CHG: 0.7,
    AVAL: 5.7,
  },
  {
    USUBJID: 'Y-36617-61423007',
    PARAMCD: 'PAMAYO',
    AVISITN: 8,
    CRIT5FL: 'N',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'Placebo',
    RACEGR1: 'WHITE',
    CHG: 0.3,
    AVAL: 5,
  },
  {
    USUBJID: 'Y-36617-61423007',
    PARAMCD: 'PAMAYO',
    AVISITN: 12,
    CRIT5FL: 'N',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'Placebo',
    RACEGR1: 'WHITE',
    CHG: 0,
    AVAL: 4.7,
  },
  {
    USUBJID: 'Y-53955-33663001',
    PARAMCD: 'PAMAYO',
    AVISITN: 12,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'Placebo',
    RACEGR1: 'NON-WHITE',
    CHG: -3.4,
    AVAL: 1.6,
  },
  {
    USUBJID: 'Y-53955-33663001',
    PARAMCD: 'PAMAYO',
    AVISITN: 20,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'Placebo',
    RACEGR1: 'NON-WHITE',
    CHG: -2,
    AVAL: 3,
  },
  {
    USUBJID: 'Y-65695-56003003',
    PARAMCD: 'PAMAYO',
    AVISITN: 8,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'ABC X MG',
    RACEGR1: 'NON-WHITE',
    CHG: -3.3,
    AVAL: 0.7,
  },
  {
    USUBJID: 'Y-65695-56003003',
    PARAMCD: 'PAMAYO',
    AVISITN: 12,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'ABC X MG',
    RACEGR1: 'NON-WHITE',
    CHG: -4,
    AVAL: 0,
  },
  {
    USUBJID: 'Y-65695-56003003',
    PARAMCD: 'PAMAYO',
    AVISITN: 20,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'ABC X MG',
    RACEGR1: 'NON-WHITE',
    CHG: -3,
    AVAL: 1,
  },
  {
    USUBJID: 'Y-65695-56003003',
    PARAMCD: 'PAMAYO',
    AVISITN: 28,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'ABC X MG',
    RACEGR1: 'NON-WHITE',
    CHG: -3.3,
    AVAL: 0.7,
  },
  {
    USUBJID: 'Y-65695-56003003',
    PARAMCD: 'PAMAYO',
    AVISITN: 36,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'ABC X MG',
    RACEGR1: 'NON-WHITE',
    CHG: -4,
    AVAL: 0,
  },
  {
    USUBJID: 'Y-65695-56003003',
    PARAMCD: 'PAMAYO',
    AVISITN: 44,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'ABC X MG',
    RACEGR1: 'NON-WHITE',
    CHG: -4,
    AVAL: 0,
  },
  {
    USUBJID: 'Y-65695-56003003',
    PARAMCD: 'PAMAYO',
    AVISITN: 52,
    CRIT5FL: 'Y',
    CRIT5: 'Clinical Response per Partial Adapted Mayo Score',
    SEX: 'M',
    TRT01P: 'ABC X MG',
    RACEGR1: 'NON-WHITE',
    CHG: -3.3,
    AVAL: 0.7,
  },
];

export default data;
